"""
fix_migrations.py
Run from inside your knowly folder (where migrations/ lives):
    python fix_migrations.py

Rewrites all migration upgrade() functions that blindly add columns
to check if the column already exists first, preventing DuplicateColumn
errors on Postgres when the column was already added manually.
"""

import os

MIGRATIONS_DIR = os.path.join(os.path.dirname(__file__), "migrations", "versions")

# ── Replacements ──────────────────────────────────────────────────────────────
# Each entry: (filename, old_upgrade_body, new_upgrade_body)

FIXES = [

    # 1. add_is_admin_to_user
    (
        "9a53a9a6c9e6_add_is_admin_to_user.py",
        """def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###""",
        """def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('profiles')]
    if 'is_admin' not in columns:
        with op.batch_alter_table('profiles', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))"""
    ),

    # 2. add_school_and_programme (d539b2d789cd)
    (
        "d539b2d789cd_add_school_and_programme_to_user.py",
        """def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('programme', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###""",
        """def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('profiles')]
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        if 'school' not in columns:
            batch_op.add_column(sa.Column('school', sa.String(length=200), nullable=True))
        if 'programme' not in columns:
            batch_op.add_column(sa.Column('programme', sa.String(length=200), nullable=True))"""
    ),

    # 3. add_can_access_all_content
    (
        "add_can_access_all_content.py",
        """def upgrade():
    op.add_column('profiles', sa.Column('can_access_all_content', sa.Boolean(), nullable=False, server_default='0'))""",
        """def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('profiles')]
    if 'can_access_all_content' not in columns:
        op.add_column('profiles', sa.Column('can_access_all_content', sa.Boolean(), nullable=False, server_default='0'))"""
    ),

    # 4. add_onboarding_skipped — uses PRAGMA (SQLite only), fix for Postgres
    (
        "add_onboarding_skipped_to_user.py",
        """def upgrade():
    conn = op.get_bind()
    cols = [row[1] for row in conn.execute(sa.text("PRAGMA table_info(profiles)"))]
    if 'onboarding_skipped' not in cols:
        op.add_column('profiles',
            sa.Column('onboarding_skipped', sa.Boolean(), nullable=False,
                      server_default=sa.false())
        )""",
        """def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('profiles')]
    if 'onboarding_skipped' not in columns:
        op.add_column('profiles',
            sa.Column('onboarding_skipped', sa.Boolean(), nullable=False,
                      server_default=sa.false())
        )"""
    ),

    # 5. add_streak_fields_to_user
    (
        "add_streak_fields_to_user.py",
        """def upgrade():
    # Add streak tracking columns to profiles table
    op.add_column('profiles', sa.Column('last_activity_date', sa.Date(), nullable=True))
    op.add_column('profiles', sa.Column('current_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('profiles', sa.Column('longest_streak', sa.Integer(), nullable=False, server_default='0'))""",
        """def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('profiles')]
    if 'last_activity_date' not in columns:
        op.add_column('profiles', sa.Column('last_activity_date', sa.Date(), nullable=True))
    if 'current_streak' not in columns:
        op.add_column('profiles', sa.Column('current_streak', sa.Integer(), nullable=False, server_default='0'))
    if 'longest_streak' not in columns:
        op.add_column('profiles', sa.Column('longest_streak', sa.Integer(), nullable=False, server_default='0'))"""
    ),

    # 6. add_xp_fields_to_user
    (
        "add_xp_fields_to_user.py",
        """def upgrade():
    # Add XP tracking columns to profiles table
    op.add_column('profiles', sa.Column('xp_points', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('profiles', sa.Column('xp_level', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('profiles', sa.Column('xp_title', sa.String(50), nullable=True))""",
        """def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('profiles')]
    if 'xp_points' not in columns:
        op.add_column('profiles', sa.Column('xp_points', sa.Integer(), nullable=False, server_default='0'))
    if 'xp_level' not in columns:
        op.add_column('profiles', sa.Column('xp_level', sa.Integer(), nullable=False, server_default='1'))
    if 'xp_title' not in columns:
        op.add_column('profiles', sa.Column('xp_title', sa.String(50), nullable=True))"""
    ),

    # 7. add_subscription_fields
    (
        "add_subscription_fields.py",
        """def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_tier', sa.String(length=20), nullable=False, server_default='free'))
        batch_op.add_column(sa.Column('subscription_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subscription_end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('free_quiz_attempts', sa.Integer(), nullable=False, server_default='3'))
        batch_op.add_column(sa.Column('free_quiz_attempts_reset_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###""",
        """def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('profiles')]
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        if 'subscription_tier' not in columns:
            batch_op.add_column(sa.Column('subscription_tier', sa.String(length=20), nullable=False, server_default='free'))
        if 'subscription_start_date' not in columns:
            batch_op.add_column(sa.Column('subscription_start_date', sa.DateTime(), nullable=True))
        if 'subscription_end_date' not in columns:
            batch_op.add_column(sa.Column('subscription_end_date', sa.DateTime(), nullable=True))
        if 'free_quiz_attempts' not in columns:
            batch_op.add_column(sa.Column('free_quiz_attempts', sa.Integer(), nullable=False, server_default='3'))
        if 'free_quiz_attempts_reset_date' not in columns:
            batch_op.add_column(sa.Column('free_quiz_attempts_reset_date', sa.Date(), nullable=True))"""
    ),

]

# ── Apply fixes ───────────────────────────────────────────────────────────────

def fix_file(filename, old, new):
    path = os.path.join(MIGRATIONS_DIR, filename)
    if not os.path.exists(path):
        print(f"[SKIP] Not found: {filename}")
        return

    with open(path, "r", encoding="utf-8", errors="replace") as f:
        content = f.read()

    # Normalize line endings for matching
    content_normalized = content.replace("\r\n", "\n")
    old_normalized = old.replace("\r\n", "\n")
    new_normalized = new.replace("\r\n", "\n")

    if old_normalized in content_normalized:
        updated = content_normalized.replace(old_normalized, new_normalized)
        with open(path, "w", encoding="utf-8") as f:
            f.write(updated)
        print(f"[FIXED] {filename}")
    else:
        print(f"[SKIP]  {filename} — pattern not matched (may already be fixed or different formatting)")


if __name__ == "__main__":
    print(f"Looking in: {MIGRATIONS_DIR}\n")
    for filename, old, new in FIXES:
        fix_file(filename, old, new)
    print("\nDone. Review changes then: git add migrations/ && git commit -m 'fix postgres migration column checks' && git push")