"""Add is_public column to QuizLeaderboard

Revision ID: 1c481a8a67a0
Revises: 68b2c9a84344
Create Date: 2026-02-27 11:44:16.019134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c481a8a67a0'
down_revision = '68b2c9a84344'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('quiz_leaderboard')]
    if 'percentage' in columns:
        op.drop_column('quiz_leaderboard', 'percentage')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_leaderboard', sa.Column('percentage', sa.FLOAT(), nullable=True))
    op.drop_constraint(None, 'quiz_leaderboard', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_leaderboard', 'post', ['post_id'], ['id'])
    op.drop_index('idx_leaderboard_post_score', table_name='quiz_leaderboard')
    op.create_index(op.f('idx_leaderboard_post_score'), 'quiz_leaderboard', ['post_id', 'score_pct', 'earned_marks', 'created_at'], unique=False)
    op.alter_column('quiz_leaderboard', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'quiz_data', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_data', 'post', ['post_id'], ['id'])
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempts', 'post', ['post_id'], ['id'])
    op.alter_column('profiles', 'xp_level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('profiles', 'xp_points',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('profiles', 'longest_streak',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('profiles', 'current_streak',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('post', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_table('_alembic_tmp_comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_comment_post')),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_comment_user')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
