"""add is_admin to user

Revision ID: 9a53a9a6c9e6
Revises: 
Create Date: 2026-02-20 07:00:56.519706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a53a9a6c9e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('profiles')]
    
    if 'is_admin' not in columns:
        with op.batch_alter_table('profiles', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
    # flask shell
