"""Add subscription and free quiz attempts fields.

Revision ID: add_subscription_fields
Revises: add_can_access_all_content
Create Date: 2026-02-23 14:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'add_subscription_fields'
down_revision = 'add_can_access_all_content'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_tier', sa.String(length=20), nullable=False, server_default='free'))
        batch_op.add_column(sa.Column('subscription_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subscription_end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('free_quiz_attempts', sa.Integer(), nullable=False, server_default='3'))
        batch_op.add_column(sa.Column('free_quiz_attempts_reset_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('free_quiz_attempts_reset_date')
        batch_op.drop_column('free_quiz_attempts')
        batch_op.drop_column('subscription_end_date')
        batch_op.drop_column('subscription_start_date')
        batch_op.drop_column('subscription_tier')

    # ### end Alembic commands ###
