"""Add quiz_assessments table

Revision ID: c4cf0f908c9d
Revises: 1c481a8a67a0
Create Date: 2026-02-27 12:36:41.798187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cf0f908c9d'
down_revision = '1c481a8a67a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_assessments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('attempt_id', sa.Integer(), nullable=False),
        sa.Column('question_index', sa.Integer(), nullable=False),
        sa.Column('score', sa.Float(), nullable=False),
        sa.Column('feedback', sa.Text(), nullable=True),
        sa.Column('assessed_by', sa.Integer(), nullable=True),
        sa.Column('assessed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['assessed_by'], ['profiles.id'], ),
        sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('attempt_id', 'question_index', name='unique_question_assessment')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_assessments')
    # ### end Alembic commands ###
