"""add school and programme to user

Revision ID: d539b2d789cd
Revises: 9a53a9a6c9e6
Create Date: 2026-02-21 19:28:50.710476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd539b2d789cd'
down_revision = '9a53a9a6c9e6'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('profiles')]
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        if 'school' not in columns:
            batch_op.add_column(sa.Column('school', sa.String(length=200), nullable=True))
        if 'programme' not in columns:
            batch_op.add_column(sa.Column('programme', sa.String(length=200), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('programme')
        batch_op.drop_column('school')

    # ### end Alembic commands ###
