"""allow_null_password_hash

Revision ID: fd6df6318fca
Revises: fa10ee43eea2
Create Date: 2026-03-11 15:20:38.555991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6df6318fca'
down_revision = 'fa10ee43eea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('profiles', 'profile_picture',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_sp_subject_id'), 'subject_programme', type_='foreignkey')
    op.drop_constraint(op.f('fk_sp_programme_id'), 'subject_programme', type_='foreignkey')
    op.create_foreign_key(None, 'subject_programme', 'programme', ['programme_id'], ['id'])
    op.create_foreign_key(None, 'subject_programme', 'subject', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject_programme', type_='foreignkey')
    op.drop_constraint(None, 'subject_programme', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sp_programme_id'), 'subject_programme', 'programme', ['programme_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_sp_subject_id'), 'subject_programme', 'subject', ['subject_id'], ['id'], ondelete='CASCADE')
    op.alter_column('profiles', 'profile_picture',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('profiles', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
